---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/prod
  prune: true
  wait: true
  force: true
  targetNamespace: prod
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  
