apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hello-world
  namespace: prod

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: hello-world
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: frontend

namespace: prod
